[package]
name = "fancy-nes-core"
version = "0.1.0"
edition = "2021"

[features]
fceux-log = []  # Enables tracing for FCEUX-style logs
nestest-log = []  # Enables tracing for PPU-less nestest test ROM

[dependencies]
lazy_static = "1.4.0"
bitflags = "1.3.2"