name: fancy-nes-mac

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  macos-x64:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install gnu-sed
      run: brew install gnu-sed
    - name: Install vcpkg
      run: |
        cargo install cargo-vcpkg
        cargo vcpkg build
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose
      
    - uses: actions/upload-artifact@v3
      with:
        name: "fancy-nes-macos-x64"
        path: |
          target/release/fancy-nes
          debug.ttf
        if-no-files-found: error
