name: fancy-nes

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  linux-x64:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install vcpkg
      run: |
        cargo install cargo-vcpkg
        cargo vcpkg build --manifest-path nes-platform/Cargo.toml
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose
      
    - uses: actions/upload-artifact@v3
      with:
        name: "fancy-nes-${{ env.GITHUB_JOB }}"
        path: target/release/nes-platform
        if-no-files-found: error

  macos-x64:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install vcpkg
      run: |
        cargo install cargo-vcpkg
        cargo vcpkg build --manifest-path nes-platform/Cargo.toml
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose
      
    - uses: actions/upload-artifact@v3
      with:
        name: "fancy-nes-${{ env.GITHUB_JOB }}"
        path: target/release/nes-platform
        if-no-files-found: error

  windows-x64:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install vcpkg
      run: |
        cargo install cargo-vcpkg
        cargo vcpkg build --manifest-path nes-platform/Cargo.toml
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose
      
    - uses: actions/upload-artifact@v3
      with:
        name: "fancy-nes-${{ env.GITHUB_JOB }}"
        path: target/release/nes-platform.exe
        if-no-files-found: error
    
