name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install SDL2
      run: sudo apt-get install -y libsdl2-dev libsdl2-ttf-dev
    - name: Install vcpkg
      run: |
        cargo install cargo-vcpkg
        cargo vcpkg build --manifest-path nes-platform/Cargo.toml
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose
      
    - uses: actions/upload-artifact@v3
      with:
        name: "fancy-nes-$GITHUB_JOB"
        path: target/release/nes-platform
        if-no-files-found: error
  macos:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install SDL2
      run: |
        brew update
        brew install sdl2 sdl2_ttf
        brew upgrade
    - name: Install vcpkg
      run: |
        cargo install cargo-vcpkg
        cargo vcpkg build --manifest-path nes-platform/Cargo.toml
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose
      
    - uses: actions/upload-artifact@v3
      with:
        name: "fancy-nes-$GITHUB_JOB"
        path: target/release/nes-platform
        if-no-files-found: error
    
